### ISSUE TITLE
Cell 16053 version 1.0.1

### ISSUE THREAD

**Issue by vzinche** [platybrowser/platybrowser#47]
![Screenshot from 2020-03-10 09-50-10](https://user-images.githubusercontent.com/32451366/76295322-b2b40900-62b4-11ea-9e8c-eabc34450aa0.png)

**Comment by vzinche** [comment]
The same with the cell 19799

**Comment by constantinpape** [comment]
@vzinche that should be fixed now, can you please check for some of your cells (note that the cell ids have probably changed compared the previous version 1.0.1)

**Comment by vzinche** [comment]
The 3d connectivity seems to be fixed, but I found a bug in the symmetric cell remapping :)
I guess it happens when cell 1 has a label A, cell 2 has label 0, and they both get remapped to the same cell C in the new version, the cell C gets label 0, not A (or maybe it just gets the label of the last cell?). 
Anyways, an example is a cell 27641 in 1.0.1 remapped from 27628 and 29253. 27628 has 'pair_index' 124, 29253 - 0, so 27641 got 0 as well, while it should have gotten 124.
Additionally, we should either change all the None's in pair_index column to 0 or vice versa, because they mean the same.

**Comment by vzinche** [comment]
I hope this was clear :D

**Comment by constantinpape** [comment]
> I hope this was clear :D

Partially :D.

From what I understand, the issue is that for cells that were separate in some version, then got (falsely) merged and then got split again, the mapping is incorrect. Is that right?

**Comment by vzinche** [comment]
Ahaha, sorry, no. They were falsely split,
and correctly merged in the new version. But the resulting cell got the label 0. The problem is : when two cells get merged, how is the new label calculated?

**Comment by constantinpape** [comment]
> Ahaha, sorry, no. They were falsely split,
> and correctly merged in the new version. But the resulting cell got the label 0. The problem is : when two cells get merged, how is the new label calculated?

Ah ok, I see.
Let's quickly discuss after the coffee meeting.

**Comment by constantinpape** [comment]
Ok, I looked into this and indeed, the mapping for objects that result from a merge was more or less random (I think it just got assigned whatever the higher original id had).
This should be fixed now and I checked that it works for the id you posted here.
Could you check for some other ids of symmetric pairs, @vzinche?

**Comment by vzinche** [comment]
Yup, seems to have worked, thanks!
