### ISSUE TITLE
Label disappears in s5

### ISSUE THREAD

**Issue by vzinche** [platybrowser/platybrowser#50]
Get ready, this is a really weird bug :)

In my training data loading I am relying on s5 resolution to calculate bounding boxes, etc, and I got an error that the label_id 16198 doesn't exist. (version 1.0.1)
This shouldn't be the case since it exists in s4 and has 2317 pixels.
Then, if I get it correctly, in s5 there should still be  `2317 / 2**3 = 289` pixels. 

Why is there nothing in s5?

**Comment by vzinche** [comment]
I was even boring enough to check some other labels, and yes, the number of pixels for them decreases ~8 times. Do you think you might have different size filters on different resolutions?

**Comment by vzinche** [comment]
different size filters on different resolutions -> Okay, that's not the case since some even smaller labels survived s4->s5 transition

**Comment by constantinpape** [comment]
> In my training data loading I am relying on s5 resolution to calculate bounding boxes, etc, and I got an error that the label_id 16198 doesn't exist. (version 1.0.1)
> This shouldn't be the case since it exists in s4 and has 2317 pixels.
> Then, if I get it correctly, in s5 there should still be `2317 / 2**3 = 289` pixels.

I think this calculation is not so straight forward; it only works if labels are approximately round or square; e.g. for completely flat objects this does not hold at all.
Could you check how this id looks in s4?

Alternatively, just calculate the bounding box from the columns `bb_min` and `bb_max` in
https://github.com/platybrowser/platybrowser/blob/more-validation/data/1.0.1/tables/sbem-6dpf-1-whole-segmented-cells/default.csv.
This is given in microns and you can use the resolution / voxel size for the scale level to get the pixel coordinates.

**Comment by vzinche** [comment]
- The object is decently roundish (pic attached)
- If I downsample it with nearest neighbor interpolation myself, I still get 252 pixels. 
- The nucleus assigned to this cell is nevertheless present in s5

You definitely have some bug here 

![Screenshot from 2020-03-25 15-05-35](https://user-images.githubusercontent.com/32451366/77545270-7b477e00-6eaa-11ea-8a49-cb574c6d4fcd.png)

**Comment by constantinpape** [comment]
My downsampling code is just a wrapper around `vigra.sampling.resize(..., order=0)` that distributes this across blocks. So unless a complete block is being dropped at s5 I don't know what is going wrong.

I can look into this at some point, but won't have time for it in the next couple of days.
In the meantime, you can use the bounding boxes from `default.csv`.

**Comment by vzinche** [comment]
"you can use the bounding boxes from default.csv." - This will require changing too much stuff, it's not just the bbs that I'm calculating from s5.
Btw, you are right, it actually just dropped the whole block. Will it take long just to rerun it? At least, this one block?

![block](https://user-images.githubusercontent.com/32451366/77549036-a54f6f00-6eaf-11ea-98d9-8f62a697b567.gif)

**Comment by constantinpape** [comment]
> Btw, you are right, it actually just dropped the whole block. Will it take long just to rerun it? At least, this one block?

No rerunning it is simple and will be fast, I can do that later.
I am a bit puzzled that this happened and did not throw an error though, but maybe I will see what's going on in the rerun.

**Comment by constantinpape** [comment]
I recomputed and it should be all there now.
Could you please check?

I don't know what went wrong in the first place; this shouldn't happen, but I don't have time to investigate now.

**Comment by vzinche** [comment]
Yes, it seems right, thanks!
