### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser#53]
@constantinpape 

I think we should add the leveling information (what happens when one clicks on the `level` button) to the repo. Maybe a file named `leveling.json` in the `misc` folder.
For platynereis the content would need to be:

```
double[] normalVector = new double[]{0.70,0.56,0.43};
```

If the file would be absent the button would not be generated. What do you think?

**Comment by constantinpape** [comment]
> I think we should add the leveling information (what happens when one clicks on the `level` button) to the repo. Maybe a file named `leveling.json` in the `misc` folder.

Yes, this is also a good solution.
Indeed it's not really a bookmark, so I prefer what you propose here compared to my idea in https://github.com/platybrowser/mmb-fiji/issues/88.

I will add it here later. For the MMB, I think we should default to just the image axis if the leveling.json is not there, what do you think?

**Comment by tischi** [comment]
> For the MMB, I think we should default to just the image axis if the leveling.json is not there, what do you think?

Not sure, because we also would like to motivate people learning the Bdv keyboard commands, where Shift+Z would just do this. I kind of rather would leave it away competely.

However, an additional "Default View" could be useful. If you get completely lost browsing in 3D it may be nice to have a "Home".  I think I would just grap the ViewerTransform after everything launched and put this behind a button. If we specify a specific ViewerTransform in the default Bookmark it would fetch this one, automatically.

**Comment by constantinpape** [comment]
> Not sure, because we also would like to motivate people learning the Bdv keyboard commands, where Shift+Z would just do this. I kind of rather would leave it away competely.
> 
> However, an additional "Default View" could be useful. If you get completely lost browsing in 3D it may be nice to have a "Home". I think I would just grap the ViewerTransform after everything launched and put this behind a button. If we specify a specific ViewerTransform in the default Bookmark it would fetch this one, automatically.

Sounds good!

**Comment by tischi** [comment]
I added here a file for testing: https://github.com/constantinpape/autophagosomes-clem/blob/master/data/10spd/misc/leveling.json

**Comment by tischi** [comment]
ok, this also works. 
for platynereis it would have to be: `0.70,0.56,0.43`

**Comment by constantinpape** [comment]
> ok, this also works.
> for platynereis it would have to be: `0.70,0.56,0.43`

Ok, I can add it to the platy repo eventually; but we should quickly talk via phone at some point tomorrow or on friday how we organize migrating the platy repo + the other covid repo to the new data layout.

**Comment by constantinpape** [comment]
Done in #55
