### ISSUE TITLE
traces missing in S3

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser#60]
@constantinpape 
Could it be that this file has the wrong name in the s3bucket?

https://github.com/platybrowser/platybrowser/blob/mobie/data/1.0.1/images/remote/sbem-6dpf-1-whole-segmented-traces.xml#L5

Maybe the "segmented" missing in s3?

**Comment by constantinpape** [comment]
I haven't actually uploaded it to the s3 yet, gonna do that soon.

**Comment by tischi** [comment]
ok! I think I will merge into master anyway, ok?

**Comment by constantinpape** [comment]
> ok! I think I will merge into master anyway, ok?

yes!

**Comment by constantinpape** [comment]
FIxed, traces are in s3 and I can load them.
